#!/bin/bash

mkdir -p /Applications/Subutai*
chown -R $USER /Applications/Subutai*

mkdir -p /usr/local/share/subutai/bin
mkdir -p /usr/local/share/subutai/etc
mkdir -p /usr/local/share/subutai/resources
mkdir -p /usr/local/share/subutai/python
mkdir -p /usr/local/share/subutai/log
chown -R $USER /usr/local/bin
chown -R $USER /usr/local/share/subutai
